import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile, readdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';

const root = fileURLToPath(new URL('..', import.meta.url));
const shaderDir = join(root, 'shaders');
const outDir = join(shaderDir, 'generated');
const compiler = process.env.SLANGC || 'slangc';
const check = process.argv.includes('--check');
const entries = [['flat', 'flatMain', 'compute'], ['present', 'vertexMain', 'vertex'], ['present', 'fragmentMain', 'fragment']];
const sources = (await readdir(shaderDir)).filter(f => f.endsWith('.slang')).sort();
const sourceHash = createHash('sha256');
for (const name of sources) sourceHash.update(name).update(await readFile(join(shaderDir, name)));
const hash = sourceHash.digest('hex');
if (check) {
  const manifest = JSON.parse(await readFile(join(outDir, 'manifest.json'), 'utf8'));
  if (JSON.stringify(Object.keys(manifest.outputs).sort()) !== JSON.stringify(entries.map(([, entry]) => `${entry}.wgsl`).sort())) throw new Error('Shader entry-point manifest mismatch: run npm run build');
  if (manifest.sourceHash !== hash) throw new Error('Stale shader sources: run npm run build (requires slangc)');
  for (const [name, expected] of Object.entries(manifest.outputs)) {
    if (createHash('sha256').update(await readFile(join(outDir, name))).digest('hex') !== expected) throw new Error(`Modified generated shader: ${name}`);
  }
  console.log('Slang source and generated WGSL hashes match.');
} else {
  const version = spawnSync(compiler, ['-version'], { encoding: 'utf8' });
  if (version.error || version.status !== 0) throw new Error(`slangc unavailable; install Slang or set SLANGC to its executable. ${version.error?.message || version.stderr}`);
  await mkdir(outDir, { recursive: true });
  const outputs = {};
  // Compile all entries successfully before replacing tracked artifacts.
  const compiled = [];
  for (const [name, entry, stage] of entries) {
    const result = spawnSync(compiler, [join(shaderDir, `${name}.slang`), '-I', shaderDir, '-target', 'wgsl', '-entry', entry, '-stage', stage], { encoding: 'utf8', maxBuffer: 16*1024*1024 });
    if (result.error || result.status !== 0) throw new Error(result.error?.message || result.stderr);
    if (result.stderr.trim()) console.warn(result.stderr.trim());
    const filename = `${entry}.wgsl`;
    const text = '// Generated by slangc; edit the .slang source, not this file.\n' + result.stdout.replaceAll('\r\n', '\n');
    compiled.push([filename, text]);
    outputs[filename] = createHash('sha256').update(text).digest('hex');
  }
  for (const [name, text] of compiled) await writeFile(join(outDir, name), text);
  await writeFile(join(outDir, 'manifest.json'), JSON.stringify({ compiler: (version.stdout+version.stderr).trim(), target: 'wgsl', sourceHash: hash, outputs }, null, 2)+'\n');
  console.log(`Compiled ${entries.length} Slang entry points to WGSL.`);
}
